opencpn:
    container_name: opencpn
    restart: unless-stopped
    image: dmaurin/opencpnarmbian:latest
    ports:
      - "10110:10110"
      - "9009:9009"
    volumes:
       - ./volumes/opencpn/:/opt/opencpn/
networks:
    default:
    name: edge-off-grid-data-aq-stack_default
    external: true
